source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'DineAround' do
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'FirebaseUI/Database'
  pod 'FirebaseUI/Storage'
  pod 'FirebaseUI/Phone'
  pod 'FirebaseUI/Auth'
  pod 'SDWebImage'
  pod 'YelpAPI'
  pod 'BrightFutures'
end
